sbatch ./launchers/horus_parallel_launcher_1.sh
sbatch ./launchers/horus_parallel_launcher_2.sh
sbatch ./launchers/horus_parallel_launcher_3.sh
sbatch ./launchers/horus_parallel_launcher_4.sh
sbatch ./launchers/horus_parallel_launcher_5.sh
sbatch ./launchers/horus_parallel_launcher_6.sh
sbatch ./launchers/horus_parallel_launcher_7.sh
sbatch ./launchers/horus_parallel_launcher_8.sh
sbatch ./launchers/horus_parallel_launcher_9.sh
sbatch ./launchers/horus_parallel_launcher_10.sh
sbatch ./launchers/horus_parallel_launcher_11.sh
sbatch ./launchers/horus_parallel_launcher_12.sh
sbatch ./launchers/horus_parallel_launcher_13.sh
sbatch ./launchers/horus_parallel_launcher_14.sh
sbatch ./launchers/horus_parallel_launcher_15.sh
sbatch ./launchers/horus_parallel_launcher_16.sh
sbatch ./launchers/horus_parallel_launcher_17.sh
sbatch ./launchers/horus_parallel_launcher_18.sh
sbatch ./launchers/horus_parallel_launcher_19.sh
sbatch ./launchers/horus_parallel_launcher_20.sh
sbatch ./launchers/horus_parallel_launcher_21.sh
sbatch ./launchers/horus_parallel_launcher_22.sh
sbatch ./launchers/horus_parallel_launcher_23.sh
sbatch ./launchers/horus_parallel_launcher_24.sh
sbatch ./launchers/horus_parallel_launcher_25.sh
sbatch ./launchers/horus_parallel_launcher_26.sh
sbatch ./launchers/horus_parallel_launcher_27.sh
